export enum ImageFormat {
  JPEG = "jpeg",
  JPG = "jpg",
  PNG = "png",
  WEBP = "webp",
  GIF = "gif",
  AVIF = "avif",
}

export enum ImageUploadError {
  INVALID_FORMAT = "INVALID_FORMAT",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  INVALID_DIMENSIONS = "INVALID_DIMENSIONS",
  COMPRESSION_FAILED = "COMPRESSION_FAILED",
  UPLOAD_FAILED = "UPLOAD_FAILED",
  CDN_UPLOAD_FAILED = "CDN_UPLOAD_FAILED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  PROCESSING_FAILED = "PROCESSING_FAILED",
}

export enum CompressionLevel {
  LOW = 85,
  MEDIUM = 75,
  HIGH = 65,
  MAXIMUM = 50,
}
